version: "3.9"
services:
  si:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    image: siprojekat:latest
    container_name: siprojekat
    ports:
      - "80:80"
    restart: on-failure:10
