version: "3.9"
services:
  si:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    image: siprojekat:latest
    container_name: siprojekat
    ports:
      - "3000:3000"
    restart: on-failure:10
