const transactions = [
  { date: "1.2.2002.", recipient: "nekom", amount: 1, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 2, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 3, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 4, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 5, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 6, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 7, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 8, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 3, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 4, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 5, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 6, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 5, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 2, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 6, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 4, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 5, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 6, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 8, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 2, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 1, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 6, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 5, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 4, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 6, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 4, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 5, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 6, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 8, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 2, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 1, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 6, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 5, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 4, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 6, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 4, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 5, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 6, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 8, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 2, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 1, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 6, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 5, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 4, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 6, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 4, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 5, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 6, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 8, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 2, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 1, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 6, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 5, status: "proccessing" },
  { date: "1.2.2002.", recipient: "nekom", amount: 4, status: "proccessing" },
];

export function getBasicTransactions(number = 10) {
  return number < transactions.length
    ? { data: transactions.slice(0, number), hasMore: true }
    : { data: transactions, hasMore: false };
}
