import axios from 'axios';
import { env } from '../../config/env';
const transactions = [
	{
		id: 1,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 1,
		status: 'proccessing1',
		currency: 'dolar',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 2,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 2,
		status: 'proccessing2',
		currency: 'dolar',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 3,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 3,
		status: 'proccessing3',
		currency: 'dolar',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 4,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 4,
		status: 'proccessing4',
		currency: 'dolar',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 5,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 5,
		status: 'proccessing5',
		currency: 'dolar',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 6,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 6,
		status: 'proccessing6',
		currency: 'dolar',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 7,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 7,
		status: 'proccessing7',
		currency: 'dolar',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 8,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 8,
		status: 'proccessing8',
		currency: 'dolar',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 9,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 3,
		status: 'proccessing9',
		currency: 'dolar',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 10,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 4,
		status: 'proccessing10',
		currency: 'dolar',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 11,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 5,
		status: 'proccessing1',
		currency: 'euro',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 12,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 6,
		status: 'proccessing1',
		currency: 'euro',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 13,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 5,
		status: 'proccessing1',
		currency: 'euro',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 14,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 2,
		status: 'proccessing1',
		currency: 'euro',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 15,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 6,
		status: 'proccessing1',
		currency: 'euro',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 16,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 4,
		status: 'proccessing1',
		currency: 'euro',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 17,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 5,
		status: 'proccessing1',
		currency: 'euro',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 18,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 6,
		status: 'proccessing1',
		currency: 'euro',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 19,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 8,
		status: 'proccessing1',
		currency: 'euro',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 20,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 2,
		status: 'proccessing2',
		currency: 'euro',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 21,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 1,
		status: 'proccessing2',
		currency: 'euro',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 22,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 6,
		status: 'proccessing2',
		currency: 'british pound',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 23,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 5,
		status: 'proccessing2',
		currency: 'british pound',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 24,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 4,
		status: 'proccessing2',
		currency: 'british pound',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 25,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 6,
		status: 'proccessing2',
		currency: 'british pound',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 26,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 4,
		status: 'proccessing2',
		currency: 'british pound',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 27,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 5,
		status: 'proccessing2',
		currency: 'british pound',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 28,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 6,
		status: 'proccessing2',
		currency: 'british pound',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 29,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 8,
		status: 'proccessing2',
		currency: 'british pound',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 30,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 2,
		status: 'proccessing3',
		currency: 'british pound',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 31,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 1,
		status: 'proccessing3',
		currency: 'british pound',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 32,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 6,
		status: 'proccessing3',
		currency: 'british pound',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 33,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 5,
		status: 'proccessing3',
		currency: 'british pound',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'VISA',
	},
	{
		id: 34,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 4,
		status: 'proccessing3',
		currency: 'BAM',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 35,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 6,
		status: 'proccessing3',
		currency: 'BAM',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 36,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 4,
		status: 'proccessing3',
		currency: 'BAM',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 37,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 5,
		status: 'proccessing3',
		currency: 'BAM',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 38,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 6,
		status: 'proccessing3',
		currency: 'BAM',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 39,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 8,
		status: 'proccessing3',
		currency: 'BAM',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 40,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 2,
		status: 'proccessing3',
		currency: 'BAM',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 41,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 1,
		status: 'proccessing3',
		currency: 'BAM',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 42,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 6,
		status: 'proccessing3',
		currency: 'BAM',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 43,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 5,
		status: 'proccessing',
		currency: 'BAM',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 44,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 4,
		status: 'proccessing',
		currency: 'CHE',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 45,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 6,
		status: 'proccessing',
		currency: 'CHE',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 46,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 4,
		status: 'proccessing',
		currency: 'CHE',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 47,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 5,
		status: 'proccessing',
		currency: 'CHE',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 48,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 6,
		status: 'proccessing',
		currency: 'CHE',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 49,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 8,
		status: 'proccessing',
		currency: 'CHE',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 50,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 2,
		status: 'proccessing',
		currency: 'CHE',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 51,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 1,
		status: 'proccessing',
		currency: 'CHE',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 52,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 6,
		status: 'proccessing',
		currency: 'CHE',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 53,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 5,
		status: 'proccessing',
		currency: 'CHE',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
	{
		id: 54,
		date: '1.2.2002.',
		recipient: 'nekom',
		amount: 4,
		status: 'proccessing?',
		currency: 'CHE',
		nameOfThePayee: 'N.N',
		bankAccount: 'XXXX XXXX XXXX XXXX',
		nameOfTheBank: 'Bank',
		methodOfPayment: 'MASTERCARD',
	},
];

export function getBasicTransactions(number = 10) {
	return number < transactions.length
		? { data: transactions.slice(0, number), hasMore: true }
		: { data: transactions, hasMore: false };
}

export function getTransactions(pageNumber, pageSize) {
	return axios(env.API_ENV.url + '/api/transactions?pageNumber=' + pageNumber + '&pageSize=' + pageSize, {
		method: 'GET',
		headers: {
			'Content-Type': 'application/json',
		},
	});
}
export function getTransactionDetails(id) {
	return axios(env.API_ENV.url + '/api/transactions/' + id, {
		method: 'GET',
		headers: {
			'Content-Type': 'application/json',
		},
	});
}
